/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * AwITeksBackendApplicationApi - axios parameter creator
 * @export
 */
export const AwITeksBackendApplicationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [myName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sayHello: async (myName?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (myName !== undefined) {
                localVarQueryParameter['myName'] = myName;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AwITeksBackendApplicationApi - functional programming interface
 * @export
 */
export const AwITeksBackendApplicationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AwITeksBackendApplicationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [myName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sayHello(myName?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sayHello(myName, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AwITeksBackendApplicationApi - factory interface
 * @export
 */
export const AwITeksBackendApplicationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AwITeksBackendApplicationApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [myName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sayHello(myName?: string, options?: any): AxiosPromise<string> {
            return localVarFp.sayHello(myName, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AwITeksBackendApplicationApi - object-oriented interface
 * @export
 * @class AwITeksBackendApplicationApi
 * @extends {BaseAPI}
 */
export class AwITeksBackendApplicationApi extends BaseAPI {
    /**
     * 
     * @param {string} [myName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AwITeksBackendApplicationApi
     */
    public sayHello(myName?: string, options?: AxiosRequestConfig) {
        return AwITeksBackendApplicationApiFp(this.configuration).sayHello(myName, options).then((request) => request(this.axios, this.basePath));
    }
}
