/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Plant } from '../models';
/**
 * PlantControllerApi - axios parameter creator
 * @export
 */
export const PlantControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add new plant, assign it to specifier user and specie
         * @param {number} userId 
         * @param {number} speciesId 
         * @param {Plant} plant 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPlant: async (userId: number, speciesId: number, plant: Plant, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('addPlant', 'userId', userId)
            // verify required parameter 'speciesId' is not null or undefined
            assertParamExists('addPlant', 'speciesId', speciesId)
            // verify required parameter 'plant' is not null or undefined
            assertParamExists('addPlant', 'plant', plant)
            const localVarPath = `/plants/{userId}/{speciesId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
                .replace(`{${"speciesId"}}`, encodeURIComponent(String(speciesId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(plant, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all plants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllPlants: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/plants`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get plant by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPlant: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPlant', 'id', id)
            const localVarPath = `/plants/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete plant by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removePlant: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('removePlant', 'id', id)
            const localVarPath = `/plants/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update plant
         * @param {Plant} plant 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePlant: async (plant: Plant, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'plant' is not null or undefined
            assertParamExists('updatePlant', 'plant', plant)
            const localVarPath = `/plants`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(plant, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PlantControllerApi - functional programming interface
 * @export
 */
export const PlantControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PlantControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add new plant, assign it to specifier user and specie
         * @param {number} userId 
         * @param {number} speciesId 
         * @param {Plant} plant 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addPlant(userId: number, speciesId: number, plant: Plant, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addPlant(userId, speciesId, plant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get all plants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllPlants(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Plant>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllPlants(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get plant by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPlant(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Plant>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPlant(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete plant by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removePlant(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removePlant(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update plant
         * @param {Plant} plant 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePlant(plant: Plant, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePlant(plant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PlantControllerApi - factory interface
 * @export
 */
export const PlantControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PlantControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Add new plant, assign it to specifier user and specie
         * @param {number} userId 
         * @param {number} speciesId 
         * @param {Plant} plant 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPlant(userId: number, speciesId: number, plant: Plant, options?: any): AxiosPromise<string> {
            return localVarFp.addPlant(userId, speciesId, plant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all plants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllPlants(options?: any): AxiosPromise<Array<Plant>> {
            return localVarFp.getAllPlants(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get plant by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPlant(id: number, options?: any): AxiosPromise<Plant> {
            return localVarFp.getPlant(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete plant by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removePlant(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.removePlant(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update plant
         * @param {Plant} plant 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePlant(plant: Plant, options?: any): AxiosPromise<void> {
            return localVarFp.updatePlant(plant, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PlantControllerApi - object-oriented interface
 * @export
 * @class PlantControllerApi
 * @extends {BaseAPI}
 */
export class PlantControllerApi extends BaseAPI {
    /**
     * 
     * @summary Add new plant, assign it to specifier user and specie
     * @param {number} userId 
     * @param {number} speciesId 
     * @param {Plant} plant 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlantControllerApi
     */
    public addPlant(userId: number, speciesId: number, plant: Plant, options?: AxiosRequestConfig) {
        return PlantControllerApiFp(this.configuration).addPlant(userId, speciesId, plant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all plants
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlantControllerApi
     */
    public getAllPlants(options?: AxiosRequestConfig) {
        return PlantControllerApiFp(this.configuration).getAllPlants(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get plant by id
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlantControllerApi
     */
    public getPlant(id: number, options?: AxiosRequestConfig) {
        return PlantControllerApiFp(this.configuration).getPlant(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete plant by id
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlantControllerApi
     */
    public removePlant(id: number, options?: AxiosRequestConfig) {
        return PlantControllerApiFp(this.configuration).removePlant(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update plant
     * @param {Plant} plant 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlantControllerApi
     */
    public updatePlant(plant: Plant, options?: AxiosRequestConfig) {
        return PlantControllerApiFp(this.configuration).updatePlant(plant, options).then((request) => request(this.axios, this.basePath));
    }
}
