/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Species } from '../models';
/**
 * SpeciesControllerApi - axios parameter creator
 * @export
 */
export const SpeciesControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add new specie
         * @param {Species} species 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addSpecie: async (species: Species, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'species' is not null or undefined
            assertParamExists('addSpecie', 'species', species)
            const localVarPath = `/species`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(species, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all species
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSpecies: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/species`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get specific specie by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpecie: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSpecie', 'id', id)
            const localVarPath = `/species/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete specie by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeSpecie: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('removeSpecie', 'id', id)
            const localVarPath = `/species/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update specie
         * @param {Species} species 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSpecie: async (species: Species, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'species' is not null or undefined
            assertParamExists('updateSpecie', 'species', species)
            const localVarPath = `/species`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(species, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SpeciesControllerApi - functional programming interface
 * @export
 */
export const SpeciesControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SpeciesControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add new specie
         * @param {Species} species 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addSpecie(species: Species, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addSpecie(species, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get all species
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllSpecies(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<object>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllSpecies(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get specific specie by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSpecie(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSpecie(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete specie by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeSpecie(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeSpecie(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update specie
         * @param {Species} species 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSpecie(species: Species, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSpecie(species, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SpeciesControllerApi - factory interface
 * @export
 */
export const SpeciesControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SpeciesControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Add new specie
         * @param {Species} species 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addSpecie(species: Species, options?: any): AxiosPromise<string> {
            return localVarFp.addSpecie(species, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all species
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSpecies(options?: any): AxiosPromise<Array<object>> {
            return localVarFp.getAllSpecies(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get specific specie by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpecie(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.getSpecie(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete specie by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeSpecie(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.removeSpecie(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update specie
         * @param {Species} species 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSpecie(species: Species, options?: any): AxiosPromise<void> {
            return localVarFp.updateSpecie(species, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SpeciesControllerApi - object-oriented interface
 * @export
 * @class SpeciesControllerApi
 * @extends {BaseAPI}
 */
export class SpeciesControllerApi extends BaseAPI {
    /**
     * 
     * @summary Add new specie
     * @param {Species} species 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpeciesControllerApi
     */
    public addSpecie(species: Species, options?: AxiosRequestConfig) {
        return SpeciesControllerApiFp(this.configuration).addSpecie(species, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all species
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpeciesControllerApi
     */
    public getAllSpecies(options?: AxiosRequestConfig) {
        return SpeciesControllerApiFp(this.configuration).getAllSpecies(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get specific specie by id
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpeciesControllerApi
     */
    public getSpecie(id: number, options?: AxiosRequestConfig) {
        return SpeciesControllerApiFp(this.configuration).getSpecie(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete specie by id
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpeciesControllerApi
     */
    public removeSpecie(id: number, options?: AxiosRequestConfig) {
        return SpeciesControllerApiFp(this.configuration).removeSpecie(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update specie
     * @param {Species} species 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpeciesControllerApi
     */
    public updateSpecie(species: Species, options?: AxiosRequestConfig) {
        return SpeciesControllerApiFp(this.configuration).updateSpecie(species, options).then((request) => request(this.axios, this.basePath));
    }
}
