/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Plant } from './plant';

/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {Plant}
     * @memberof Activity
     */
    'plant': Plant;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    'activityType': ActivityActivityTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    'date': string;
}

export const ActivityActivityTypeEnum = {
    Watering: 'WATERING',
    Fertilisation: 'FERTILISATION'
} as const;

export type ActivityActivityTypeEnum = typeof ActivityActivityTypeEnum[keyof typeof ActivityActivityTypeEnum];


