/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddActivityRequestBody
 */
export interface AddActivityRequestBody {
    /**
     * 
     * @type {number}
     * @memberof AddActivityRequestBody
     */
    'plantId': number;
    /**
     * 
     * @type {string}
     * @memberof AddActivityRequestBody
     */
    'activityType': AddActivityRequestBodyActivityTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AddActivityRequestBody
     */
    'date': string;
}

export const AddActivityRequestBodyActivityTypeEnum = {
    Watering: 'WATERING',
    Fertilisation: 'FERTILISATION'
} as const;

export type AddActivityRequestBodyActivityTypeEnum = typeof AddActivityRequestBodyActivityTypeEnum[keyof typeof AddActivityRequestBodyActivityTypeEnum];


