/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ForumPostUserIncluded
 */
export interface ForumPostUserIncluded {
    /**
     * 
     * @type {number}
     * @memberof ForumPostUserIncluded
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ForumPostUserIncluded
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof ForumPostUserIncluded
     */
    'userName': string;
    /**
     * 
     * @type {string}
     * @memberof ForumPostUserIncluded
     */
    'creationDate': string;
}

