/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {User} from './user';

/**
 * 
 * @export
 * @interface ForumPost
 */
export interface ForumPost {
    /**
     * 
     * @type {number}
     * @memberof ForumPost
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ForumPost
     */
    'content': string;
    /**
     * 
     * @type {User}
     * @memberof ForumPost
     */
    'author': User;
    /**
     * 
     * @type {string}
     * @memberof ForumPost
     */
    'date': string;
}

