/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ForumThreadSummaryResponseBody
 */
export interface ForumThreadSummaryResponseBody {
    /**
     * 
     * @type {number}
     * @memberof ForumThreadSummaryResponseBody
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ForumThreadSummaryResponseBody
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ForumThreadSummaryResponseBody
     */
    'creatorName': string;
    /**
     * 
     * @type {string}
     * @memberof ForumThreadSummaryResponseBody
     */
    'creationDate': string;
    /**
     * 
     * @type {number}
     * @memberof ForumThreadSummaryResponseBody
     */
    'postsCount': number;
    /**
     * 
     * @type {boolean}
     * @memberof ForumThreadSummaryResponseBody
     */
    'isFollowed': boolean;
}

