/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PlantSummary
 */
export interface PlantSummary {
    /**
     * 
     * @type {number}
     * @memberof PlantSummary
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PlantSummary
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PlantSummary
     */
    'speciesName': string;
    /**
     * 
     * @type {boolean}
     * @memberof PlantSummary
     */
    'isFavourite': boolean;
    /**
     * 
     * @type {string}
     * @memberof PlantSummary
     */
    'imgUrl': string;
}

