/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserPlantSummary
 */
export interface UserPlantSummary {
    /**
     * 
     * @type {string}
     * @memberof UserPlantSummary
     */
    'plantName': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserPlantSummary
     */
    'activityTypes': Array<UserPlantSummaryActivityTypesEnum>;
}

export const UserPlantSummaryActivityTypesEnum = {
    Watering: 'WATERING',
    Fertilisation: 'FERTILISATION'
} as const;

export type UserPlantSummaryActivityTypesEnum = typeof UserPlantSummaryActivityTypesEnum[keyof typeof UserPlantSummaryActivityTypesEnum];


