/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserForumThreadsSummary } from './user-forum-threads-summary';
import { UserPlantSummary } from './user-plant-summary';

/**
 * 
 * @export
 * @interface UserMainSummary
 */
export interface UserMainSummary {
    /**
     * 
     * @type {Array<UserPlantSummary>}
     * @memberof UserMainSummary
     */
    'missedActivities': Array<UserPlantSummary>;
    /**
     * 
     * @type {Array<UserPlantSummary>}
     * @memberof UserMainSummary
     */
    'incomingActivities': Array<UserPlantSummary>;
    /**
     * 
     * @type {Array<UserForumThreadsSummary>}
     * @memberof UserMainSummary
     */
    'forumThreads': Array<UserForumThreadsSummary>;
}

