/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserForumThreadsSummary
 */
export interface UserForumThreadsSummary {
    /**
     * 
     * @type {number}
     * @memberof UserForumThreadsSummary
     */
    'forumThreadId': number;
    /**
     * 
     * @type {string}
     * @memberof UserForumThreadsSummary
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof UserForumThreadsSummary
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof UserForumThreadsSummary
     */
    'date': string;
}

