name: Backend Test CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Gradle Project
        run: ./gradlew build --no-daemon -x test
      - name: Test Gradle Project
        run: ./gradlew test