name: Backend Test CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    services:
      mysql:
        image: mysql:5.7.38
        env:
          MYSQL_DATABASE: db
          MYSQL_USER: user
          MYSQL_PASSWORD: my-secret-pw
          MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Gradle Project
        run: ./gradlew build
      - name: Test Gradle Project
        run: ./gradlew test
